# Generated by Django 4.1.7 on 2023-03-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fuerza', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sigilo', models.IntegerField()),
                ('percepcion', models.IntegerField()),
                ('persuasion', models.IntegerField()),
                ('atletismo', models.IntegerField()),
                ('craft', models.IntegerField()),
            ],
        ),
    ]
