# Generated by Django 4.1.7 on 2023-03-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_equipamiento_puntos_armadura_equipamiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caballo',
            name='inventario',
            field=models.IntegerField(default=0),
        ),
    ]
